package com.shelpatrick.a18

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.ArrayAdapter
import android.widget.Spinner
import kotlinx.android.synthetic.main.activity_agencias_mizrahi.*

class AgenciasMizrahiActivity : AppCompatActivity() {
    lateinit var ageMizrahi:Spinner

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_agencias_mizrahi)

        ageMizrahi=findViewById(R.id.SpinnerMizrahi)

        var ageMizrahis= arrayListOf(
            "445     Acre           Ben Ami 47 ",
            "474     Afula          Jerusalem 4",
            "454     Alon Shvut     Mahale Michael 5",
            "489     Arad           Sderot Chen 34",
            "416     Ashdod         Rogozin 3",
            "615     Ashdod         Haorgim 11",
            "502     Ashdod         Jerusalem 12",
            "427     Ashkelon       Katznelson 5",
            "490     Ashkelon       Edmond De Rotshild",
            "554     Bat Yam        Balfur 110",
            "425     Bat Yam        Balfur 58",
            "426     Beer Sheva     Kern Hyesod 31",
            "544     Beer Sheva     Keren Kayemet 130",
            "566     Beer Sheva     Negev Center Buildig",
            "583     Beni Barak     Jerusalem 24",
            "570     Beni Barak     Kahanman 108",
            "439     Bet Shean      Shaul Hamelekh 85",
            "567     Bet Shemesh    Yigal Alon 6",
            "430     Bnei Brak      Rabi Tarpon 1",
            "468     Bnei Brak      Hazon Ish 13",
            "513     Carmiel        Hachroshet 9",
            "456     Dimona         Ha-nasi Blvd",
            "470     Eilat          Shderot Ha-tmarim 1",
            "530     Givat Shmuel   Menachem Begin Blvd 38",
            "455     Givatayim      Weizman 65",
            "420     Hadera         Herzl 23",
            "449     Haifa          Ha-nasi Blvd 137",
            "441     Haifa          HaNeviim 26",
            "444     Haifa          Pal Yam 11",
            "505     Haifa          Andrei Sacharov 6",
            "492     Haifa          Trumpeldor 54",
            "564     Haifa          Pal Yam 11",
            "593     Harish         Derech Eretz 33",
            "415     Herzliya       Sokolov 6",
            "522     Herzliya       Aba Even 12",
            "512     Hod Hasharon   Derech Ramatym 108",
            "412     Holon          Sokolov 95",
            "419     Holon          Hamasbir 19",
            "411     Holon          Golda Meir 7",
            "555     Holon          Sokolov 48",
            "591     Jerusalem      Agripas 88",
            "401b    Jerusalem      Ben Yehuda 12",
            "417     Jerusalem      Malkhei Israel 16",
            "458     Jerusalem      Givat Shaul 24",
            "568     Jerusalem      Heleni Hamalka 9",
            "539     Jerusalem      Kanfei Nesharim 7",
            "459     Jerusalem      Tiferet Israel 16",
            "569     Jerusalem      Paran 5",
            "563     Jerusalem      Golda Meir Blvd 255",
            "479     Jerusalem      Shemuel Bayit 12",
            "517     Jerusalem      Yad Harustim 15",
            "463     Kafar Qasim    Ali ibn Abi Taleb",
            "538     Kafar Yassif   D. Senter",
            "483     Karnei Shomron Rehavam Zevi 1",
            "526     Kefar Saba     Weizmann 61",
            "533     Kefar Saba     Hataas 13",
            "647     Kefar Saba     Weizmann 132",
            "424     Kefar Saba     Hataas 13",
            "448     Kiryat Ata     Zevulun 4",
            "518     Kiryat Bialick Derech Akko 194",
            "433     Kiryat Gat     Lachish Blvd 11",
            "450     kiryat malakhi Jabotinsky 22",
            "467     Kiryat ono     Hcalanit 2",
            "487     Kiryat Shmona  Tel Chai Blvd 77",
            "446     Kiryat Yam     Jerusalem 3",
            "418     Lod            Tavor Airport City",
            "546     Lod            Aba Hill Silver 13",
            "558     Maalot         Shelomo Sharira 3",
            "552     Migdal Haemeq  Shaul Amor Blvd 77",
            "521     Modiin         Lev Hair 2",
            "443     Nahariya       Gaaton 27",
            "559     Nazereth       Hagalil 22",
            "511     Nes Tziona     Habanim 5",
            "447     Nesher         Derech Bar Yehuda 63",
            "553     Netanya        Bareket 3",
            "541     Netanya        Mapi 5",
            "542     Netanya        Beny Berma 2",
            "669     Netanya        Smilanski 4",
            "428     Netivot        Jerusalem 17",
            "560     Nof Hagalil    Commercial Center Upper",
            "437     Ofakim         Herzel 32",
            "438     Or Akiva       Vayzman 1",
            "473     Pardes Hana    Habanim 17",
            "481     Petah Tikva    Hanessiim 45",
            "519     Petah Tikva    Shenkar 14",
            "548     Petah Tikva    Hahazmaot 65",
            "429     Petah Tikva    Bar Kochba 12-18",
            "431     Petah Tikva    Hasivim 2",
            "465     Petah Tikva    Rothschild 73",
            "561     Raanana        Zarhin 13",
            "496     Raanana        Ahuza 96",
            "423     Raanana        Ahuza 96",
            "414     Ramat Gan      Bar Ilan University",
            "515     Ramat Gan      Ben Gurion 38",
            "466     Ramat Gan      Jabotinski 1",
            "534     Ramat Gan      Landau 6",
            "551     Ramat Gan      Jabotinsky 3",
            "413     Ramat Gan      Arlozorov 1",
            "477     Ramat Gan      Jabotinsky 7",
            "472     Ramat Hasharon Sokolov 67",
            "432     Ramle          Herzl 92",
            "532     Rehovot        Pekric 3",
            "657     Rehovot        Herzl 163",
            "434     Rehovot        Herzl 35",
            "529     Rishon Lezion  Moreshet Israel 15",
            "435     Rishon Lezion  Herzl 73",
            "495     Rishon Lezion  Lishanski 3",
            "543     Rosh Hayin     Shabazi 55",
            "585     Saknin         Hagalil 217",
            "484     Sderot         Haplada Alley 8",
            "581     Shfaram        Sultan Basha Alatrash",
            "442     Shlomi         Gaz Station",
            "589     Taibe          Mahmoud Darwish",
            "421     Tel Aviv-Yafo  Ibn Gvirol 71",
            "407     Tel Aviv-Yafo  Hashmonaim 123",
            "406     Tel Aviv-Yafo  Salame 4",
            "469     Tel Aviv-Yafo  Salame 54",
            "478     Tel Aviv-Yafo  Ben Yehuda 25",
            "524     Tel Aviv-Yafo  Waizman 32-34",
            "528     Tel Aviv-Yafo  Habarzel 26",
            "453     Tel Aviv-Yafo  Dizengoff 45",
            "547     Tel Aviv-Yafo  Amir Gilboa 14",
            "493     Tel Aviv-Yafo  Tagor 38",
            "408     Tel Aviv-Yafo  Rival 7",
            "409     Tel Aviv-Yafo  Alenby 105",
            "557     Tel Aviv-Yafo  94 Yigal Allon",
            "462     Tiberias       Habanim Corner Hayarden",
            "537     Um El Fahem    Main Road,town hall",
            "540     Yavne          Hdugit 16",
            "525     Yehud          Moshe Dayan 3",
            "514     Yehud          Ha'Atzmaut 16",
            "582     Yokneam        Hatamar 2",
            "562     Zefat          Aliya B' 4",
            "590     Zichron Yaakov Hanadiv 13")

        ageMizrahi.adapter= ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,ageMizrahis)


        BtnVoltarAgenMizrahi.setOnClickListener {
            val intent=Intent(this,BancosActivity::class.java)
            startActivity(intent)
        }
    }
}
